name: test

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Issue/PR number'
        required: true

jobs:
  single-comment:
    runs-on: ubuntu-20.04
    name: Single comment progress
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Single comment create
        uses: hasura/comment-progress@test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'hasura/comment-progress'
          number: ${{ github.event.inputs.number }}
          id: single-comment
          message: 'Just a plain simple comment to report progress'

      - name: Do some work
        run: echo "this step just prints this"

      - name: Single comment update
        uses: hasura/comment-progress@test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'hasura/comment-progress'
          number: ${{ github.event.inputs.number }}
          id: single-comment
          message: 'The comment is updated.'

      - name: Single comment append
        uses: hasura/comment-progress@test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'hasura/comment-progress'
          number: ${{ github.event.inputs.number }}
          id: single-comment
          append: true
          message: 'The comment will be appended with this text.'

  fail-comment:
    runs-on: ubuntu-20.04
    name: Fail comment progress
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Should comment and fail this job
        uses: hasura/comment-progress@test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'hasura/comment-progress'
          number: ${{ github.event.inputs.number }}
          id: fail-comment
          fail: true
          message: ':x: This comment is to denote an error'
