name: test

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Issue/PR number'
        required: true

jobs:
  single-comment:
    runs-on: ubuntu-20.04
    name: Single comment progress
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Single comment on an issue or PR
        uses: hasura/comment-progress@main
        with:
          repository: 'hasura/comment-progress'
          number: ${{ github.event.inputs.number }}
          id: single-comment
          message: 'Just a plain simple comment to progress report'
